girlscript/GirlScript-Summer-of-Code

- index.html
- projects.html
Changed Description, navigation bar issue on mobile version fixed, Banners are working fine again.
> All basic issues solved.

- css/index.css
now the button is working 😊
resolves issue #1
> Corrected z-index

- schedule.html
<Do not remove this template and always check the preview before making the PR>
Description: <provide a description>
typo fix on schedule.html
> typo fix on schedule.html

- css/index.css
- index.html
> adding sponsor slider

- css/index.css
- css/team.css
- css/timeline.css
- index.html
- js/campus_ambassador.js
- js/common/init.js
- js/team.js
- resource/2021/data_team.js
- schedule.html
- team.html
Changed the following:
1. Fixed Navbar
2. Fixed Schedule
3. Fixed About GirlScript - tech logo
4. Changed team - 4 grids
> final changes

- css/index.css
- index.html
1. Changed the About GirlScript content
2. Solved the alignment issue of Participant and Mentor Buttons
> about gssoc and button changes

- css/index.css
- index.html
> All Links Working

- index.html
Added target attribute to 'a' tag in the registration section to open the google forms in new tab. Fixes #18.
> added target attribute to 'a' tag

- FAQs.html
- campus_ambassador.html
- code-of-conduct.html
- gssoc18.html
- gssoc19.html
- gssoc20.html
- index.html
- leaderboard.html
- profile.html
- projects.html
- resource/2021/data_team.js
- review.html
- schedule.html
- team.html
Added GSSOC - 20 Archive Page and their projects
> Added GSSOC-20 Archive

- css/style.css
- schedule.html
> Changed Background Color of schedule.html

- schedule.html
Description: I have resolved the typo on the schedule page
> Typo resolved 

- campus_ambassador.html
- css/campus_ambassador.css
- css/team.css
- team.html
> team and ca design fixed

- resource/2020/data_project_list.js
Updated the issues by Project mentors told before 2:53 AM.....
> Updated projects

- resource/2020/data_project_list.js
Added YouTube URLs for Vision of Projects.
> Update vision of projects

- js/project.js
- projects.html
- resource/2020/data_project_list.js
* Update 'Vision' with 'Project Video'
* Made the links clickable
> Convert url text to links

- resource/2020/data_project_list.js
Hello, In the projects section in girlscript summer of code, My (Vedha Krishna Yarasuri) project (Flow2Ml) link is not the correct one. So in this PR, I have edited the link. Now it is the correct link. Hope You would correct the link.
Thank You
> Flow2Ml Link edit by owner

- resource/2020/data_project_list.js
- schedule.html
Updated Timeline and updated some projects.
> Timeline Update

- projects.html
- resource/2020/data_project_list.js
Added mentors upto project id 33
> Added Mentors for 33 projects

- leaderboard.html
- profile.html
Hey, made these two changes here:
> Added alert message for Leaderboard and Profile.

- resource/2020/data_project_list.js
After internally discussing with the mentors, we have decided to change the technology stack(backend only) of our project. 
Please accept the change so that contributors are not misled.
PS: I am the admin of this project.
> Update Backend stack of Opportunity Calendar

- resource/2020/data_project_list.js
> Updated Mentors

- resource/2020/data_project_list.js
- My Project _**lifeMEDeasy**_ was getting redirected to _**Recess**_ my other project when maximized.
- Updated Resource link from **`avinashkranjan/Recess`** to **`avinashkranjan/lifeMEDeasy`**
> Updated 'lifeMEDeasy' Project Link

- resource/2020/data_project_list.js
6 repository added of project sakura in the gssoc project list
> projectsakura update on js

- resource/2020/data_project_list.js
> Added mentor details

- leaderboard.html
- resource/2020/data_results.js
Hi team,
I have rebased and updated the leaderboard data with the current one (15th April 7:20 pm IST).
Thanks.
> Updated Leaderboard Data.

- resource/2020/data_project_list.js
There is a need for the project demo video to be changed has as new functionalities were introduced. This could help contributors while choosing projects for their contribution.
> Updated project demo video.

- resource/2020/data_project_list.js
Update project name on the website since our team has decided to change the project name from `BlogSite` to `WordNook`. (Permission was taken from GSSoC team before changing project name)
Also removed inactive mentor from the list. (Inactive since 1 month)
> Update project name

- resource/2020/data_project_list.js
Please can anyone have a look at this, we just added one more repo to our organisation
> Blog repo added in the projectsakura project 

- resource/2020/data_project_list.js
Transferred the Personal project to Organization.
So the URL changed
> Update makesmatheasy and documentation repo URL
